# Thông tin định danh dự án trên SonarQube 
sonar.projectKey=DevSecOps_Nhom10
sonar.projectName=DevSecOps_Nhom10

# Thư mục chứa mã nguồn cần quét 
sonar.sources=app


# Địa chỉ của SonarQube (Dùng domain nội bộ của Kubernetes để kết nối cho bảo mật)
sonar.host.url=http://sonarqube-release-sonarqube.sonarqube.svc.cluster.local:9000

# Chỉ định rõ SCM để SonarQube track được ai commit dòng code nào
sonar.scm.provider=git

# Loại bỏ các thư mục như bên dưới khỏi quá trình quét SAST
sonar.exclusions=app/.deploystack/**,app/.github/**,app/helm-chart/**,app/docs/**,**/*.json,**/*.yaml,**/node_modules/**


