apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-gateway
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: nt548-observability
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: otel-gateway
      app.kubernetes.io/name: opentelemetry-collector
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
