apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: app
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200" # URL của Vault Server
      path: "devsecops_nhom10_kv" # Mount path của KV engine
      version: "v2"
      auth:
        kubernetes:
          # Trỏ tới Vault Role đã tạo ở Bước 2
          mountPath: "kubernetes"
          role: "eso-role"
          # Dùng chính ServiceAccount vừa tạo ở trên để định danh với Vault
          serviceAccountRef:
            name: eso-vault-sa
            