apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devsecops
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: NT548 DevSecOps Project
  sourceRepos:
    - https://github.com/nqvuong23/NT548-DevSecOps-Project.git
  destinations:
    - namespace: app
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: argo-rollouts
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
