apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: devsecops
  source:
    repoURL: https://github.com/nqvuong23/NT548-DevSecOps-Project.git
    targetRevision: main
    path: helm-chart/microservices
    helm:
      releaseName: online-boutique
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
