apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: frontend-rps-scaler
  namespace: app
  labels:
    app.kubernetes.io/name: frontend-rps-scaler
    app.kubernetes.io/part-of: nt548-autoscaling
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: frontend
  pollingInterval: 15
  cooldownPeriod: 120
  minReplicaCount: 2
  maxReplicaCount: 6
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      name: frontend-rps-keda-hpa
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Pods
              value: 2
              periodSeconds: 30
        scaleDown:
          stabilizationWindowSeconds: 120
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        metricName: nginx_ingress_app_rps
        query: sum(rate(nginx_ingress_controller_requests{namespace="app", ingress="app"}[1m]))
        threshold: "20"
        activationThreshold: "5"
