apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scenario3-isolate-runtime-threat
  namespace: app
  labels:
    scenario: security-scenario-3
spec:
  podSelector:
    matchLabels:
      app: scenario3-runtime-threat
  policyTypes:
    - Ingress
    - Egress
