#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR_REL="demo-scripts/output/scenario3"
OUT_DIR="${ROOT_DIR}/${OUT_DIR_REL}"

APP_NAMESPACE="${APP_NAMESPACE:-app}"
MONITORING_NAMESPACE="${MONITORING_NAMESPACE:-monitoring}"
RUNTIME_POD="${RUNTIME_POD:-scenario3-runtime-threat}"
ROLLOUT_NAME="${ROLLOUT_NAME:-scenario3-security-demo}"
VULNERABLE_IMAGE="${VULNERABLE_IMAGE:-nginx:1.16}"

log() {
  printf '[scenario3] %s\n' "$*"
}

die() {
  printf '[scenario3] ERROR: %s\n' "$*" >&2
  exit 1
}

have() {
  command -v "$1" >/dev/null 2>&1
}

usage() {
  cat <<'EOF'
Usage:
  bash demo-scripts/scenario3-security-sim.sh <command>

Commands:
  status            Check local tools and Kubernetes resources.
  production        Apply persistent Scenario 3 Kyverno policy and quarantine NetworkPolicy.
  secret            Create a temporary fake leak under app_src and run Gitleaks.
  image             Run Trivy against an intentionally vulnerable public image.
  alert-rule        Apply the Scenario 3 PrometheusRule.
  runtime           Create a short-lived BusyBox pod and execute suspicious commands for Falco.
  isolate           Apply a NetworkPolicy that isolates the runtime demo pod.
  rollout           Run the Argo Rollouts abort demo with a failing AnalysisTemplate.
  rollback          Revert the rollout demo image back to the stable version.
  cleanup           Remove Scenario 3 demo Kubernetes resources.
  all               Run secret, image, alert-rule, runtime, and rollout.

Environment:
  APP_NAMESPACE=app
  MONITORING_NAMESPACE=monitoring
  VULNERABLE_IMAGE=nginx:1.16
EOF
}

ensure_out_dir() {
  mkdir -p "${OUT_DIR}"
}

run_gitleaks() {
  if have gitleaks; then
    gitleaks "$@"
  elif have docker; then
    docker run --rm -v "${ROOT_DIR}:/repo" -w /repo zricethezav/gitleaks:v8.18.2 "$@"
  else
    return 127
  fi
}

run_trivy() {
  if have trivy; then
    trivy "$@"
  elif have docker; then
    docker run --rm -v "${ROOT_DIR}:/work" -w /work aquasec/trivy:0.50.1 "$@"
  else
    return 127
  fi
}

kubectl_ready() {
  have kubectl && kubectl version --request-timeout=5s >/dev/null 2>&1
}

render_manifest() {
  sed "s/namespace: app/namespace: ${APP_NAMESPACE}/g" "$1"
}

status_demo() {
  log "repository: ${ROOT_DIR}"
  log "output dir: ${OUT_DIR_REL}"

  for tool in kubectl helm docker gitleaks trivy k6; do
    if have "${tool}"; then
      log "${tool}: found"
    else
      log "${tool}: missing"
    fi
  done

  if kubectl_ready; then
    log "kubectl context: ready"
    kubectl get ns "${APP_NAMESPACE}" "${MONITORING_NAMESPACE}" 2>/dev/null || true
    kubectl get crd rollouts.argoproj.io scaledobjects.keda.sh prometheusrules.monitoring.coreos.com 2>/dev/null || true
    kubectl get deploy,rollout,hpa -n "${APP_NAMESPACE}" 2>/dev/null || true
    kubectl get scaledobject -n "${APP_NAMESPACE}" 2>/dev/null || true
    kubectl get clusterpolicy nt548-scenario3-workload-baseline 2>/dev/null || true
    kubectl get networkpolicy scenario3-quarantine -n "${APP_NAMESPACE}" 2>/dev/null || true
    kubectl get servicemonitor -A 2>/dev/null | grep -Ei 'falco|keda|ingress' || true
    kubectl get pods -A | grep -Ei 'falco|kyverno|defect|rollout|keda|prometheus|grafana' || true
  else
    log "kubectl context: unavailable from this shell"
  fi
}

production_demo() {
  kubectl_ready || die "kubectl context is not ready."
  cd "${ROOT_DIR}"
  log "Applying persistent Scenario 3 production security controls"
  kubectl apply -f k8s-manifest/security/scenario3-production.yaml
  kubectl get clusterpolicy nt548-scenario3-workload-baseline
  kubectl get networkpolicy scenario3-quarantine -n "${APP_NAMESPACE}"
}

secret_demo() {
  ensure_out_dir
  cd "${ROOT_DIR}"

  local leak_file="app_src/frontend/scenario3_demo_leak.txt"
  rm -f "${leak_file}"

  log "Creating a temporary fake secret file: ${leak_file}"
  {
    printf '# Scenario 3 fake leak. This file is generated by the demo script and removed automatically.\n'
    printf 'NT548_TOKEN="%s%s"\n' "demo-leak-" "1234567890"
  } > "${leak_file}"

  set +e
  run_gitleaks detect \
    --no-git \
    --source ./app_src \
    --config .gitleaks.toml \
    --verbose \
    --report-format json \
    --report-path "${OUT_DIR_REL}/gitleaks-report.json"
  local exit_code=$?
  set -e

  rm -f "${leak_file}"

  if [ "${exit_code}" -eq 1 ]; then
    log "Expected result: Gitleaks detected the fake hardcoded secret."
    log "Report: ${OUT_DIR_REL}/gitleaks-report.json"
  elif [ "${exit_code}" -eq 0 ]; then
    die "Gitleaks did not detect the fake secret. Check .gitleaks.toml rules."
  else
    die "Gitleaks failed with exit code ${exit_code}. Install gitleaks or Docker."
  fi
}

image_demo() {
  ensure_out_dir
  cd "${ROOT_DIR}"

  log "Scanning intentionally vulnerable image: ${VULNERABLE_IMAGE}"
  set +e
  run_trivy image \
    --cache-dir "${OUT_DIR_REL}/.trivy-cache" \
    --scanners vuln \
    --format json \
    --output "${OUT_DIR_REL}/trivy-vulnerable-image-report.json" \
    --exit-code 1 \
    --severity HIGH,CRITICAL \
    --ignore-unfixed \
    "${VULNERABLE_IMAGE}"
  local exit_code=$?
  set -e

  if [ "${exit_code}" -eq 1 ] && [ -s "${OUT_DIR_REL}/trivy-vulnerable-image-report.json" ]; then
    log "Expected result: Trivy found HIGH/CRITICAL vulnerabilities."
    log "Report: ${OUT_DIR_REL}/trivy-vulnerable-image-report.json"
  elif [ "${exit_code}" -eq 0 ]; then
    die "Trivy did not find HIGH/CRITICAL issues in ${VULNERABLE_IMAGE}. Try VULNERABLE_IMAGE=python:3.8-slim-buster."
  else
    die "Trivy failed with exit code ${exit_code}. Install trivy or Docker."
  fi
}

alert_rule_demo() {
  kubectl_ready || die "kubectl context is not ready."
  cd "${ROOT_DIR}"
  log "Applying Scenario 3 PrometheusRule in namespace ${MONITORING_NAMESPACE}"
  sed "s/namespace: monitoring/namespace: ${MONITORING_NAMESPACE}/g" \
    helm-chart/observation/prometheus-stack/rules/nt548-scenario3-security-alerts.yaml \
    | kubectl apply -f -
  kubectl get prometheusrule nt548-scenario3-security-alerts -n "${MONITORING_NAMESPACE}"
}

runtime_demo() {
  kubectl_ready || die "kubectl context is not ready."
  cd "${ROOT_DIR}"

  log "Creating runtime threat demo pod in namespace ${APP_NAMESPACE}"
  render_manifest demo-scripts/scenario3/runtime-threat-pod.yaml | kubectl apply -f -
  kubectl wait pod/"${RUNTIME_POD}" -n "${APP_NAMESPACE}" --for=condition=Ready --timeout=90s

  log "Executing commands that Falco commonly flags: shell spawn and sensitive file read"
  kubectl exec -n "${APP_NAMESPACE}" "${RUNTIME_POD}" -- sh -c 'id >/dev/null; cat /etc/shadow >/dev/null 2>&1 || true; sh -c "echo scenario3-runtime-shell >/dev/null"'

  log "Check Falco/Falcosidekick runtime signal:"
  log "  kubectl logs -n security -l app.kubernetes.io/name=falco --tail=50"
  log "  PromQL: sum(increase(falco_events_total[5m])) by (rule, priority)"
}

isolate_demo() {
  kubectl_ready || die "kubectl context is not ready."
  cd "${ROOT_DIR}"
  log "Labeling ${RUNTIME_POD} for the persistent quarantine NetworkPolicy"
  kubectl apply -f k8s-manifest/security/scenario3-production.yaml
  kubectl label pod "${RUNTIME_POD}" -n "${APP_NAMESPACE}" security.nt548/quarantine=true --overwrite
  kubectl get networkpolicy scenario3-quarantine -n "${APP_NAMESPACE}"
  kubectl get pod "${RUNTIME_POD}" -n "${APP_NAMESPACE}" --show-labels
}

rollout_demo() {
  kubectl_ready || die "kubectl context is not ready."
  cd "${ROOT_DIR}"

  kubectl get crd rollouts.argoproj.io >/dev/null 2>&1 || die "Argo Rollouts CRD is missing."

  log "Applying Rollout and failing AnalysisTemplate"
  render_manifest demo-scripts/scenario3/rollout-security-demo.yaml | kubectl apply -f -
  sleep 10
  kubectl get rollout "${ROLLOUT_NAME}" -n "${APP_NAMESPACE}" || true

  log "Updating rollout image to the risky version. The analysis job exits 1, so the rollout should abort."
  if have kubectl && kubectl argo rollouts version >/dev/null 2>&1; then
    kubectl argo rollouts set image "${ROLLOUT_NAME}" rollouts-demo=argoproj/rollouts-demo:red -n "${APP_NAMESPACE}"
  else
    kubectl patch rollout "${ROLLOUT_NAME}" -n "${APP_NAMESPACE}" --type=json \
      -p='[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"argoproj/rollouts-demo:red"}]'
  fi

  for _ in $(seq 1 18); do
    kubectl get rollout "${ROLLOUT_NAME}" -n "${APP_NAMESPACE}" || true
    kubectl get analysisrun -n "${APP_NAMESPACE}" | grep "${ROLLOUT_NAME}" || true
    sleep 5
  done

  log "Expected result: rollout becomes Degraded/Aborted and stable ReplicaSet remains available."
  log "Detailed view: kubectl argo rollouts get rollout ${ROLLOUT_NAME} -n ${APP_NAMESPACE}"
}

rollback_demo() {
  kubectl_ready || die "kubectl context is not ready."
  cd "${ROOT_DIR}"

  log "Reverting rollout demo to stable image"
  if kubectl argo rollouts version >/dev/null 2>&1; then
    kubectl argo rollouts undo "${ROLLOUT_NAME}" -n "${APP_NAMESPACE}" || true
    kubectl argo rollouts set image "${ROLLOUT_NAME}" rollouts-demo=argoproj/rollouts-demo:blue -n "${APP_NAMESPACE}" || true
  else
    kubectl patch rollout "${ROLLOUT_NAME}" -n "${APP_NAMESPACE}" --type=json \
      -p='[{"op":"replace","path":"/spec/template/spec/containers/0/image","value":"argoproj/rollouts-demo:blue"}]' || true
  fi
  kubectl get rollout "${ROLLOUT_NAME}" -n "${APP_NAMESPACE}" || true
}

cleanup_demo() {
  cd "${ROOT_DIR}"
  if kubectl_ready; then
    log "Cleaning Kubernetes resources"
    kubectl label pod "${RUNTIME_POD}" -n "${APP_NAMESPACE}" security.nt548/quarantine- 2>/dev/null || true
    render_manifest demo-scripts/scenario3/runtime-threat-pod.yaml | kubectl delete -f - --ignore-not-found=true
    render_manifest demo-scripts/scenario3/rollout-security-demo.yaml | kubectl delete -f - --ignore-not-found=true
  fi
  rm -f "${ROOT_DIR}/app_src/frontend/scenario3_demo_leak.txt"
  log "Cleanup complete"
}

cmd="${1:-}"
case "${cmd}" in
  status) status_demo ;;
  production) production_demo ;;
  secret) secret_demo ;;
  image) image_demo ;;
  alert-rule) alert_rule_demo ;;
  runtime) runtime_demo ;;
  isolate) isolate_demo ;;
  rollout) rollout_demo ;;
  rollback) rollback_demo ;;
  cleanup) cleanup_demo ;;
  all)
    secret_demo
    image_demo
    alert_rule_demo
    runtime_demo
    rollout_demo
    ;;
  -h|--help|help|"") usage ;;
  *) usage; die "Unknown command: ${cmd}" ;;
esac
